name: CI Workflow
 
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build Maven
      run: mvn clean install
    - name: Test
      run: mvn test -DskipTests=false

  install-mysql:
    name: Install MySQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server mysql-client
          sudo systemctl start mysql
          sudo systemctl enable mysql
          sudo systemctl status mysql

