name: Integration Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
            mysql database: 'webappDB'
            mysql user: '${{secrets.DATABASE_USERNAME}}'
            mysql password: '${{secrets.DATABASE_PASSWORD}}'

      - name: Run Tests
        run: mvn test
        
      - name: Build
        run: mvn clean install



