name: Integration Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    name: Integration Test
    runs-on: ubuntu-latest
    env:
      DATABASE: webappDB
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # - name: Start MySQL
      #   run: |
      #     sudo /etc/init.d/mysql start
      #     mysql -h 127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS $DATABASE;" -u$DATABASE_USERNAME -p$DATABASE_PASSWORD

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'webappDB'
          mysql user: 'web-app'
          mysql password: '${{ secrets.DATABASE_PASSWORD }}'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest" 
 
      - name: Run packer init
        id: init
        run: packer init main.pkr.hcl
 
      - name: Run packer fmt
        run: packer fmt --check main.pkr.hcl
 
      - name: Fail if packer fmt fails
        if: ${{ steps.setup.outputs.exit-code != 0 }}
        run: exit 1

      - name: Run packer validate
        run: packer validate main.pkr.hcl
 
      - name: Fail if packer validate fails
        if: ${{ steps.setup.outputs.exit-code != 0 }}
        run: exit 1
 
      



