name: Packer Build Custom Image
 
on:
  pull_request:
   types: [closed]
 
jobs:
  packer_init_validate_build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      DATABASE: webappDB
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
    name: Build Custom Image with Java Spring Boot Application artifacts
    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
 
      - name: Zip all the webApp files
        run: |
          zip -r webapp.zip ./
          pwd
      - name: check the current
        run: ls -la

      - name: Setup google config
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS}}

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'webappDB'
          mysql user: 'web-app'
          mysql password: '${{ secrets.DATABASE_PASSWORD }}'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"
 
      - name: Run `packer init`
        id: init
        run: packer init .

      - name: Packer build
        id: build
        run: packer build main.pkr.hcl

        

  
     
     